// KTLT Essay Questions - Đề tự luận
// Source: Cuối kì 20201 (Đề 1,2,3,4) + Ôn tập
// IDs start at 500
// =============================================
const ktltEssay = [
  // ==================== ĐỀ 1 (Cuối kì 20201) ====================
  {
    id:500, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 1 (2.0 điểm)</strong><br><br>"
      + "Theo em, kỹ thuật Template function có thể kết hợp vào đa năng hóa toán tử (operator overloading) được không? "
      + "Nếu được thì có lợi ích gì? Hãy minh họa bằng 1 ví dụ cụ thể là đa năng hóa toán tử + cho số phức.",
    answer:"Có, kỹ thuật Template function hoàn toàn có thể kết hợp với đa năng hóa toán tử (operator overloading). "
      + "Lợi ích: giúp viết mã tổng quát, có thể tái sử dụng cho nhiều kiểu dữ liệu khác nhau (int, float, double, ...) "
      + "mà không cần viết lại code cho mỗi kiểu, giảm trùng lặp và tăng tính bảo trì.<br><br>"
      + "Ví dụ minh họa với toán tử + cho số phức:<br><br>"
      + "<pre><code>template &lt;typename T&gt;\n"
      + "struct Complex {\n"
      + "    T real, img;\n"
      + "    Complex(T r = 0, T i = 0) : real(r), img(i) {}\n"
      + "};\n"
      + "\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator+(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real + b.real, a.img + b.img);\n"
      + "}\n"
      + "\n"
      + "// Sử dụng với int:\n"
      + "Complex&lt;int&gt; c1(1, 2), c2(3, 4);\n"
      + "Complex&lt;int&gt; c3 = c1 + c2;  // c3.real = 4, c3.img = 6\n"
      + "\n"
      + "// Sử dụng với double:\n"
      + "Complex&lt;double&gt; d1(1.5, 2.5), d2(3.5, 4.5);\n"
      + "Complex&lt;double&gt; d3 = d1 + d2;  // d3.real = 5.0, d3.img = 7.0</code></pre>"
  },
  {
    id:501, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 2 (2.0 điểm)</strong><br><br>"
      + "Khi định nghĩa phép toán cộng ma trận cho cấu trúc MATRIX được định nghĩa như sau:<br><br>"
      + "<pre><code>typedef struct {\n    int Row, Col;\n    float ** Data;\n} MATRIX;</code></pre><br>"
      + "Một sinh viên nhận thấy, nếu thực hiện biểu thức C = A + B một vài lần thì kết quả OK, nhưng nếu biểu thức "
      + "đó nằm trong 1 vòng lặp lớn (hàng ngàn lần) thì kết quả không còn đúng, thậm chí khi tăng số lần lặp, "
      + "chương trình còn bị lỗi run-time, mặc dù các hàm cấp phát bộ nhớ, định nghĩa toán tử cộng ma trận SV đã "
      + "làm rất chuẩn. Em hãy cho biết tại sao và đưa ra giải pháp!<br><br>"
      + "<pre><code>MATRIX operator+(MATRIX A, MATRIX B) {\n    MATRIX temp;\n    temp.Row = A.Row;\n    temp.Col = A.Col;\n    AllocMatrix(temp);\n    /* Phần cộng ma trận ... */\n    return temp;\n}</code></pre>",
    answer:"Nguyên nhân: Hàm operator+ trả về MATRIX theo kiểu truyền bằng trị (return by value). "
      + "Khi đó, trình biên dịch tạo một bản sao tạm thời của temp để trả về. "
      + "Tuy nhiên, MATRIX chứa con trỏ Data (float**), và việc sao chép mặc định (shallow copy) chỉ copy địa chỉ của con trỏ, "
      + "không copy dữ liệu mảng hai chiều. Kết quả là biến temp (cục bộ trong hàm) và bản sao tạm thời cùng trỏ vào một vùng nhớ. "
      + "Khi kết thúc hàm, temp bị hủy (hoặc vùng nhớ bị giải phóng), bản sao tạm thời trở thành con trỏ treo (dangling pointer). "
      + "Sau nhiều lần lặp, vùng nhớ bị cấp phát và giải phóng liên tục gây lỗi run-time (double free, memory corruption).<br><br>"
      + "Giải pháp 1 - Copy constructor (deep copy): Định nghĩa hàm sao chép sâu để mỗi bản sao có vùng nhớ riêng.<br><br>"
      + "<pre><code>MATRIX operator+(const MATRIX&amp; A, const MATRIX&amp; B) {\n"
      + "    MATRIX temp;\n"
      + "    temp.Row = A.Row;\n"
      + "    temp.Col = A.Col;\n"
      + "    AllocMatrix(temp);\n"
      + "    for (int i = 0; i &lt; temp.Row; i++)\n"
      + "        for (int j = 0; j &lt; temp.Col; j++)\n"
      + "            temp.Data[i][j] = A.Data[i][j] + B.Data[i][j];\n"
      + "    return temp;\n"
      + "}</code></pre><br>"
      + "Giải pháp 2 - Truyền tham chiếu và dùng output parameter:<br><br>"
      + "<pre><code>void MatrixAdd(const MATRIX&amp; A, const MATRIX&amp; B, MATRIX&amp; C) {\n"
      + "    C.Row = A.Row; C.Col = A.Col;\n"
      + "    AllocMatrix(C);\n"
      + "    for (int i = 0; i &lt; C.Row; i++)\n"
      + "        for (int j = 0; j &lt; C.Col; j++)\n"
      + "            C.Data[i][j] = A.Data[i][j] + B.Data[i][j];\n"
      + "}</code></pre>"
  },
  {
    id:502, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 3 (1.0 điểm)</strong><br><br>"
      + "Tinh chỉnh để nâng cao hiệu năng của chương trình sau:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n{\n    int i = 0, found = 0;\n    while ((!found) && (i < n)) {\n        float x = log(b) / log(2);\n        if (a[i] == x) found = 1;\n        else i++;\n    }\n    if (found) do_something;\n}</code></pre>",
    answer:"Các tinh chỉnh để nâng cao hiệu năng:<br><br>"
      + "1. Đưa biểu thức log(b)/log(2) ra ngoài vòng lặp (loop-invariant code motion): "
      + "Giá trị này không thay đổi trong suốt vòng lặp, nên tính một lần trước khi vào vòng lặp.<br>"
      + "2. Dùng for thay vì while: Cấu trúc for rõ ràng hơn, thường được compiler tối ưu tốt hơn.<br>"
      + "3. Dùng break thay vì biến found: Thoát vòng lặp ngay khi tìm thấy, không cần biến cờ.<br>"
      + "4. So sánh số thực với epsilon: Không nên dùng == cho float vì sai số làm tròn. Dùng fabs(a[i] - x) &lt; 1e-6.<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n"
      + "{\n"
      + "    float x = log(b) / log(2);\n"
      + "    for (int i = 0; i &lt; n; i++) {\n"
      + "        if (fabs(a[i] - x) &lt; 1e-6) {\n"
      + "            do_something;\n"
      + "            break;\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:503, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 4 (2.0 điểm)</strong><br><br>"
      + "Một sinh viên xây dựng chức năng sắp xếp sinh viên theo thứ tự kiểu Việt Nam (theo tên rồi mới "
      + "đến họ và tên lót) từ 1 danh sách họ và tên sinh viên của lớp như sau:<br><br>"
      + "<pre><code>// #include ...\nint i, j, k, n = 0;\nchar ds[500][30], tg[30];\nvoid bosung(); void sapxep(); void inds();\n\nint main() {\n    // hàm main\n}\n\nint NamePos(char *ht)\n{\n    i = strlen(ht) - 1;\n    while (ht[i] == ' ' && i > -1) i--;\n    while (ht[i] != ' ' && i > -1) i--;\n    return i + 1;\n}\n\nvoid sapxep() {\n    for (i = 0; i < n - 1; i++) {\n        k = i;\n        for (j = i + 1; j < n; j++)\n            if (strcmp(ds[k] + NamePos(ds[k]),\n                       ds[j] + NamePos(ds[j])) > 0) k = j;\n            else if (strcmp(ds[k] + NamePos(ds[k]),\n                            ds[j] + NamePos(ds[j])) == 0)\n                if (strcmp(ds[k], ds[j]) > 0) k = j;\n        if (k != i) {\n            strcpy(tg, ds[i]);\n            strcpy(ds[i], ds[j]);\n            strcpy(ds[j], tg);\n        }\n    }\n    printf(\"\\n Danh sach da duoc sap xep !!!\");\n    getch();\n}</code></pre><br>"
      + "Hãy tìm và sửa lại lỗi của các đoạn code trên!",
    answer:"Có hai lỗi chính trong đoạn code:<br><br>"
      + "<strong>Lỗi 1 - Biến toàn cục i bị thay đổi (runtime logic error):</strong><br>"
      + "Biến i là biến toàn cục (global int i). Hàm NamePos sử dụng i làm biến chạy trong vòng lặp while, "
      + "làm thay đổi giá trị của i. Khi NamePos được gọi từ vòng lặp for trong sapxep (cũng dùng i làm biến chạy), "
      + "giá trị của i bị thay đổi, gây ra hành vi không xác định và sắp xếp sai.<br><br>"
      + "<strong>Lỗi 2 - Swap nhầm biến (logic error):</strong><br>"
      + "Trong hàm sapxep, sau khi tìm được chỉ số k của phần tử nhỏ nhất, lệnh swap viết sai:<br>"
      + "<code>strcpy(ds[i], ds[j]);</code> thay vì <code>strcpy(ds[i], ds[k]);</code><br>"
      + "Do đó, ds[i] được gán bằng ds[j] (phần tử cuối cùng của vòng lặp trong) thay vì ds[k] (phần tử nhỏ nhất tìm được).<br><br>"
      + "Code sửa lại:<br><br>"
      + "<pre><code>int NamePos(char *ht)\n"
      + "{\n"
      + "    int pos = strlen(ht) - 1;\n"
      + "    while (ht[pos] == ' ' &amp;&amp; pos &gt; -1) pos--;\n"
      + "    while (ht[pos] != ' ' &amp;&amp; pos &gt; -1) pos--;\n"
      + "    return pos + 1;\n"
      + "}\n"
      + "\n"
      + "void sapxep() {\n"
      + "    int i, j, k;\n"
      + "    char tg[30];\n"
      + "    for (i = 0; i &lt; n - 1; i++) {\n"
      + "        k = i;\n"
      + "        for (j = i + 1; j &lt; n; j++)\n"
      + "            if (strcmp(ds[k] + NamePos(ds[k]),\n"
      + "                       ds[j] + NamePos(ds[j])) &gt; 0) k = j;\n"
      + "            else if (strcmp(ds[k] + NamePos(ds[k]),\n"
      + "                            ds[j] + NamePos(ds[j])) == 0)\n"
      + "                if (strcmp(ds[k], ds[j]) &gt; 0) k = j;\n"
      + "        if (k != i) {\n"
      + "            strcpy(tg, ds[i]);\n"
      + "            strcpy(ds[i], ds[k]);  // sửa j -&gt; k\n"
      + "            strcpy(ds[k], tg);\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:504, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 5 (2.0 điểm)</strong><br><br>"
      + "Cho cấu trúc danh sách liên kết đôi như sau:<br><br>"
      + "<pre><code>struct Node {\n    int data;\n    Node *next, *prev;\n};</code></pre><br>"
      + "Hãy viết hàm đảo ngược danh sách:<br>"
      + "<pre><code>Node* reverse(Node* head) { ... }</code></pre><br>"
      + "a) Sử dụng đệ quy (1 điểm)<br>"
      + "b) Không sử dụng đệ quy (1 điểm)",
    answer:"<strong>a) Giải pháp đệ quy:</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    if (head == NULL || head-&gt;next == NULL)\n"
      + "        return head;\n"
      + "    Node* newHead = reverse(head-&gt;next);\n"
      + "    head-&gt;next-&gt;next = head;\n"
      + "    head-&gt;next-&gt;prev = head-&gt;next;\n"
      + "    head-&gt;next = NULL;\n"
      + "    head-&gt;prev = newHead;\n"
      + "    Node* p = newHead;\n"
      + "    while (p-&gt;next != NULL) p = p-&gt;next;\n"
      + "    p-&gt;prev = NULL;\n"
      + "    return newHead;\n"
      + "}</code></pre><br>"
      + "<strong>b) Giải pháp không đệ quy (dùng 3 con trỏ):</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    Node *prev = NULL, *curr = head, *next = NULL;\n"
      + "    while (curr != NULL) {\n"
      + "        next = curr-&gt;next;\n"
      + "        curr-&gt;next = prev;\n"
      + "        curr-&gt;prev = next;\n"
      + "        prev = curr;\n"
      + "        curr = next;\n"
      + "    }\n"
      + "    return prev;\n"
      + "}</code></pre>"
  },
  {
    id:505, label:"Cuối kì 20201 - Đề 1",
    text:"<strong>Đề 1 - Câu 6 (1.0 điểm)</strong><br><br>"
      + "(a) (0.5 điểm) Hãy cho biết sự khác nhau của hai cách khai báo giá trị: 'x' và \"x\". Hãy mô tả cách biểu diễn trong bộ nhớ của cả hai giá trị.<br><br>"
      + "(b) (0.5 điểm) Cho đoạn chương trình sau đây, hãy tìm ra ít nhất hai lỗi sai trong chương trình và sửa lại chương trình cho đúng:<br><br>"
      + "<pre><code>int main(void) {\n    char *s = \"abcde\";\n    int len = strlen(s);\n    for (int i = 0; i <= len; i++)\n        s[i] += 1;\n    return printf(\"'%s' is %d characters long\\n\", ++s, strlen(s));\n}</code></pre>",
    answer:"<strong>(a) Sự khác nhau giữa 'x' và \"x\":</strong><br><br>"
      + "'x' là một ký tự (character) - kiểu char, kích thước 1 byte, chứa mã ASCII của chữ 'x' (0x78).<br>"
      + "\"x\" là một chuỗi ký tự (string literal) - kiểu const char[2], gồm 2 byte: ký tự 'x' (0x78) và ký tự kết thúc chuỗi '\\0' (0x00).<br>"
      + "Trong bộ nhớ: 'x' chiếm 1 ô nhớ, \"x\" chiếm 2 ô nhớ liên tiếp.<br><br>"
      + "<strong>(b) Các lỗi trong chương trình và cách sửa:</strong><br><br>"
      + "<strong>Lỗi 1 - Undefined behavior: Ghi vào string literal.</strong><br>"
      + "Biến s là con trỏ char* trỏ đến hằng chuỗi \"abcde\" (string literal nằm trong vùng nhớ read-only). "
      + "Việc thực hiện s[i] += 1 cố gắng ghi đè vào vùng nhớ chỉ đọc, gây undefined behavior (có thể crash).<br>"
      + "Cách sửa: dùng mảng char có thể thay đổi: <code>char s[] = \"abcde\";</code><br><br>"
      + "<strong>Lỗi 2 - Off-by-one: i &lt;= len gây tràn bộ nhớ.</strong><br>"
      + "strlen(\"abcde\") = 5. Vòng lặp for chạy i = 0, 1, 2, 3, 4, 5. "
      + "Khi i = 5, s[5] là ký tự null '\\0' (kết thúc chuỗi). Ghi đè lên s[5] làm hỏng dấu kết thúc chuỗi, "
      + "dẫn đến lỗi khi in hoặc các thao tác xử lý chuỗi sau đó.<br>"
      + "Cách sửa: đổi thành <code>i &lt; len</code>.<br><br>"
      + "<strong>Lỗi 3 - ++s làm mất địa chỉ gốc (nếu dùng con trỏ).</strong><br>"
      + "Nếu dùng char* s thay vì mảng, ++s làm s trỏ đến phần tử thứ 2, gây mất địa chỉ gốc "
      + "(và gây memory leak nếu có cấp phát động). Nhưng nếu dùng mảng char s[] thì ++s là lỗi compile.<br><br>"
      + "Chương trình sửa lại hoàn chỉnh:<br><br>"
      + "<pre><code>int main(void) {\n"
      + "    char s[] = \"abcde\";\n"
      + "    int len = strlen(s);\n"
      + "    for (int i = 0; i &lt; len; i++)\n"
      + "        s[i] += 1;\n"
      + "    printf(\"'%s'\\n\", s);\n"
      + "    return 0;\n"
      + "}</code></pre>"
  },

  // ==================== ĐỀ 2 (Cuối kì 20201) ====================
  {
    id:506, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 1 (2.0 điểm)</strong><br><br>"
      + "Một sinh viên xây dựng chức năng sắp xếp sinh viên theo thứ tự kiểu Việt Nam (theo tên rồi mới "
      + "đến họ và tên lót) từ 1 danh sách họ và tên sinh viên của lớp như sau:<br><br>"
      + "<pre><code>// #include ...\nint i, j, k, n = 0;\nchar ds[500][30], tg[30];\nvoid bosung(); void sapxep(); void inds();\n\nint main() {\n    // hàm main\n}\n\nchar *Name(char *ht)\n{\n    i = strlen(ht) - 1;\n    while (ht[i] == ' ') i--;\n    while (ht[i] != ' ') i--;\n    return ht + i + 1;\n}\n\nvoid sapxep() {\n    for (i = 0; i < n - 1; i++) {\n        k = i;\n        for (j = i + 1; j < n; j++)\n            if (strcmp(Name(ds[k]), Name(ds[j])) > 0) k = j;\n            else if (strcmp(Name(ds[k]), Name(ds[j])) == 0)\n                if (strcmp(ds[k], ds[j]) > 0) k = j;\n        if (k != i) {\n            strcpy(tg, ds[i]);\n            strcpy(ds[i], ds[j]);\n            strcpy(ds[j], tg);\n        }\n    }\n    printf(\"\\n Danh sach da duoc sap xep !!!\");\n    getch();\n}</code></pre><br>"
      + "Hãy tìm và sửa lại lỗi của các đoạn code trên!",
    answer:"Có hai lỗi chính trong đoạn code:<br><br>"
      + "<strong>Lỗi 1 - Biến toàn cục i bị thay đổi (runtime logic error):</strong><br>"
      + "Biến i là biến toàn cục. Hàm Name sử dụng i làm biến tạm để duyệt chuỗi, "
      + "làm thay đổi giá trị của i khi đang ở vòng lặp for trong sapxep. "
      + "Điều này làm cho vòng lặp chạy sai, dẫn đến kết quả sắp xếp không đúng.<br><br>"
      + "<strong>Lỗi 2 - Swap nhầm biến (logic error):</strong><br>"
      + "Trong hàm sapxep, sau khi tìm được chỉ số k (phần tử nhỏ nhất), lệnh "
      + "<code>strcpy(ds[i], ds[j]);</code> ghi sai. Phải là <code>strcpy(ds[i], ds[k]);</code> "
      + "vì ds[k] mới là phần tử nhỏ nhất, còn ds[j] là phần tử đang xét cuối cùng trong vòng lặp trong.<br><br>"
      + "Code sửa lại:<br><br>"
      + "<pre><code>char *Name(char *ht)\n"
      + "{\n"
      + "    int pos = strlen(ht) - 1;\n"
      + "    while (ht[pos] == ' ') pos--;\n"
      + "    while (ht[pos] != ' ') pos--;\n"
      + "    return ht + pos + 1;\n"
      + "}\n"
      + "\n"
      + "void sapxep() {\n"
      + "    int i, j, k;\n"
      + "    char tg[30];\n"
      + "    for (i = 0; i &lt; n - 1; i++) {\n"
      + "        k = i;\n"
      + "        for (j = i + 1; j &lt; n; j++)\n"
      + "            if (strcmp(Name(ds[k]), Name(ds[j])) &gt; 0) k = j;\n"
      + "            else if (strcmp(Name(ds[k]), Name(ds[j])) == 0)\n"
      + "                if (strcmp(ds[k], ds[j]) &gt; 0) k = j;\n"
      + "        if (k != i) {\n"
      + "            strcpy(tg, ds[i]);\n"
      + "            strcpy(ds[i], ds[k]);  // sửa j -&gt; k\n"
      + "            strcpy(ds[k], tg);\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:507, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 2 (2.0 điểm)</strong><br><br>"
      + "Khi định nghĩa phép toán cộng ma trận cho cấu trúc MATRIX được định nghĩa như sau:<br><br>"
      + "<pre><code>typedef struct {\n    int Row, Col;\n    float ** Data;\n} MATRIX;</code></pre><br>"
      + "Một sinh viên nhận thấy, nếu thực hiện biểu thức C = A + B một vài lần thì kết quả OK, nhưng nếu biểu thức "
      + "đó nằm trong 1 vòng lặp lớn (hàng ngàn lần) thì kết quả không còn đúng, thậm chí khi tăng số lần lặp, "
      + "chương trình còn bị lỗi run-time, mặc dù các hàm cấp phát bộ nhớ, định nghĩa toán tử cộng ma trận SV đã "
      + "làm rất chuẩn. Em hãy cho biết tại sao và đưa ra giải pháp!<br><br>"
      + "<pre><code>MATRIX operator+(MATRIX A, MATRIX B) {\n    MATRIX temp;\n    temp.Row = A.Row;\n    temp.Col = A.Col;\n    AllocMatrix(temp);\n    /* Phần cộng ma trận ... */\n    return temp;\n}</code></pre>",
    answer:"Nguyên nhân: Hàm operator+ trả về MATRIX theo giá trị (return by value). Khi đó, trình biên dịch tạo bản sao tạm thời của biến temp. "
      + "Tuy nhiên, cấu trúc MATRIX chứa con trỏ float** Data; việc sao chép mặc định chỉ là shallow copy (sao chép địa chỉ con trỏ), "
      + "không tạo vùng nhớ mới. Biến temp (cục bộ) và bản sao tạm thời cùng trỏ vào một vùng dữ liệu. "
      + "Sau khi hàm kết thúc, temp bị hủy (hoặc vùng nhớ bị thu hồi), bản sao tạm thời chứa con trỏ treo (dangling pointer). "
      + "Khi lặp hàng nghìn lần, các thao tác cấp phát/giải phóng liên tục dẫn đến lỗi run-time (double free, memory corruption).<br><br>"
      + "<strong>Giải pháp 1 - Dùng tham chiếu hằng và trả về bằng tham chiếu ra (output parameter):</strong><br><br>"
      + "<pre><code>void MatrixAdd(const MATRIX&amp; A, const MATRIX&amp; B, MATRIX&amp; C) {\n"
      + "    C.Row = A.Row; C.Col = A.Col;\n"
      + "    AllocMatrix(C);\n"
      + "    for (int i = 0; i &lt; C.Row; i++)\n"
      + "        for (int j = 0; j &lt; C.Col; j++)\n"
      + "            C.Data[i][j] = A.Data[i][j] + B.Data[i][j];\n"
      + "}</code></pre><br>"
      + "<strong>Giải pháp 2 - Định nghĩa copy constructor thực hiện deep copy (C++):</strong><br><br>"
      + "<pre><code>struct MATRIX {\n"
      + "    int Row, Col;\n"
      + "    float** Data;\n"
      + "    MATRIX() : Row(0), Col(0), Data(NULL) {}\n"
      + "    MATRIX(const MATRIX&amp; m) : Row(m.Row), Col(m.Col) {\n"
      + "        AllocMatrix(*this);\n"
      + "        for (int i = 0; i &lt; Row; i++)\n"
      + "            for (int j = 0; j &lt; Col; j++)\n"
      + "                Data[i][j] = m.Data[i][j];\n"
      + "    }\n"
      + "    ~MATRIX() { FreeMatrix(*this); }\n"
      + "    MATRIX&amp; operator=(const MATRIX&amp; m) {\n"
      + "        if (this != &amp;m) {\n"
      + "            FreeMatrix(*this);\n"
      + "            Row = m.Row; Col = m.Col;\n"
      + "            AllocMatrix(*this);\n"
      + "            for (int i = 0; i &lt; Row; i++)\n"
      + "                for (int j = 0; j &lt; Col; j++)\n"
      + "                    Data[i][j] = m.Data[i][j];\n"
      + "        }\n"
      + "        return *this;\n"
      + "    }\n"
      + "};</code></pre>"
  },
  {
    id:508, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 3 (1.0 điểm)</strong><br><br>"
      + "Tinh chỉnh để nâng cao hiệu năng của đoạn code sau:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n{\n    int i = 0, found = 0;\n    float x;\n    for (; i < n; i++) {\n        x = log(b) / log(2);\n        if (a[i] == x) found = 1;\n        i++;\n    }\n    if (found) do_something;\n}</code></pre>",
    answer:"Các vấn đề và tinh chỉnh:<br><br>"
      + "1. <strong>Loop-invariant code motion:</strong> Biểu thức <code>x = log(b) / log(2)</code> được tính lại mỗi lần lặp dù giá trị không đổi. "
      + "Cần đưa ra ngoài vòng lặp.<br>"
      + "2. <strong>Lỗi tăng i hai lần:</strong> Vòng lặp for có <code>i++</code> trong phần điều khiển và <code>i++</code> trong thân vòng lặp. "
      + "Điều này khiến i tăng 2 đơn vị mỗi bước, bỏ sót phần tử. Cần chỉ tăng i ở một chỗ.<br>"
      + "3. <strong>Biến found không cần thiết:</strong> Dùng break để thoát ngay khi tìm thấy.<br>"
      + "4. <strong>So sánh float với ==:</strong> Có thể sai số. Nên dùng epsilon.<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n"
      + "{\n"
      + "    float x = log(b) / log(2);\n"
      + "    for (int i = 0; i &lt; n; i++) {\n"
      + "        if (fabs(a[i] - x) &lt; 1e-6) {\n"
      + "            do_something;\n"
      + "            break;\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:509, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 4 (2.0 điểm)</strong><br><br>"
      + "Theo em, kỹ thuật Template function có thể kết hợp vào đa năng hóa toán tử (operator overloading) được không? "
      + "Nếu được thì có lợi ích gì? Hãy minh họa bằng 1 ví dụ cụ thể là đa năng hóa toán tử - cho số phức.",
    answer:"Có, kỹ thuật Template function hoàn toàn có thể kết hợp với đa năng hóa toán tử (operator overloading). "
      + "Lợi ích: giúp tạo ra các toán tử tổng quát, hoạt động được trên nhiều kiểu dữ liệu khác nhau "
      + "(int, float, double, ...) mà chỉ cần viết code một lần, tránh trùng lặp và dễ bảo trì.<br><br>"
      + "Ví dụ minh họa với toán tử - (trừ) cho số phức:<br><br>"
      + "<pre><code>template &lt;typename T&gt;\n"
      + "struct Complex {\n"
      + "    T real, img;\n"
      + "    Complex(T r = 0, T i = 0) : real(r), img(i) {}\n"
      + "};\n"
      + "\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator-(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real - b.real, a.img - b.img);\n"
      + "}\n"
      + "\n"
      + "// Sử dụng với int:\n"
      + "Complex&lt;int&gt; c1(5, 7), c2(2, 3);\n"
      + "Complex&lt;int&gt; c3 = c1 - c2;  // c3.real = 3, c3.img = 4\n"
      + "\n"
      + "// Sử dụng với double:\n"
      + "Complex&lt;double&gt; d1(5.5, 7.5), d2(2.5, 3.5);\n"
      + "Complex&lt;double&gt; d3 = d1 - d2;  // d3.real = 3.0, d3.img = 4.0</code></pre>"
  },
  {
    id:510, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 5 (2.0 điểm)</strong><br><br>"
      + "Cho cấu trúc danh sách liên kết đôi như sau:<br><br>"
      + "<pre><code>struct Node {\n    int data;\n    Node *next, *prev;\n};</code></pre><br>"
      + "Hãy viết hàm đảo ngược danh sách:<br>"
      + "<pre><code>Node* reverse(Node* head) { ... }</code></pre><br>"
      + "a) Sử dụng đệ quy (1 điểm)<br>"
      + "b) Không sử dụng đệ quy (1 điểm)",
    answer:"<strong>a) Giải pháp đệ quy:</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    if (head == NULL || head-&gt;next == NULL)\n"
      + "        return head;\n"
      + "    Node* newHead = reverse(head-&gt;next);\n"
      + "    head-&gt;next-&gt;next = head;\n"
      + "    head-&gt;prev = head-&gt;next;\n"
      + "    head-&gt;next = NULL;\n"
      + "    return newHead;\n"
      + "}</code></pre><br>"
      + "<strong>b) Giải pháp không đệ quy (dùng 3 con trỏ):</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    Node *prev = NULL, *curr = head;\n"
      + "    while (curr != NULL) {\n"
      + "        Node* next = curr-&gt;next;\n"
      + "        curr-&gt;next = prev;\n"
      + "        curr-&gt;prev = next;\n"
      + "        prev = curr;\n"
      + "        curr = next;\n"
      + "    }\n"
      + "    return prev;\n"
      + "}</code></pre>"
  },
  {
    id:511, label:"Cuối kì 20201 - Đề 2",
    text:"<strong>Đề 2 - Câu 6 (1.0 điểm)</strong><br><br>"
      + "(a) (0.5 điểm) Hãy cho biết sự khác nhau của hai cách khai báo giá trị: 'x' và \"x\". Hãy mô tả cách biểu diễn trong bộ nhớ của cả hai giá trị.<br><br>"
      + "(b) (0.5 điểm) Cho đoạn chương trình sau đây, hãy tìm ra ít nhất hai lỗi sai trong chương trình và sửa lại chương trình cho đúng:<br><br>"
      + "<pre><code>int main(void) {\n    char *s = \"abcde\";\n    int len = strlen(s);\n    for (int i = 0; i <= len; i++)\n        s[i] += 1;\n    return printf(\"'%s' is %d characters long\\n\", ++s, strlen(s));\n}</code></pre>",
    answer:"<strong>(a) Sự khác nhau giữa 'x' và \"x\":</strong><br><br>"
      + "'x' là một ký tự đơn (kiểu char, 1 byte), chứa giá trị ASCII của 'x' (0x78).<br>"
      + "\"x\" là một chuỗi hằng (string literal, kiểu const char[2]), chiếm 2 byte: 'x' (0x78) và ký tự null '\\0' (0x00) kết thúc chuỗi.<br><br>"
      + "<strong>(b) Các lỗi trong chương trình:</strong><br><br>"
      + "<strong>Lỗi 1:</strong> <code>char *s = \"abcde\";</code> là con trỏ trỏ đến string literal (vùng nhớ read-only). "
      + "Việc <code>s[i] += 1</code> cố gắng ghi vào vùng nhớ không thể ghi, gây undefined behavior.<br>"
      + "Cách sửa: dùng mảng <code>char s[] = \"abcde\";</code>.<br><br>"
      + "<strong>Lỗi 2:</strong> Vòng lặp <code>i &lt;= len</code> với len = 5 chạy i = 0..5. Khi i = 5, s[5] là ký tự '\\0' (kết thúc chuỗi). "
      + "Ghi đè lên s[5] làm hỏng dấu kết thúc chuỗi.<br>"
      + "Cách sửa: đổi thành <code>i &lt; len</code>.<br><br>"
      + "<strong>Lỗi 3:</strong> <code>++s</code> trong printf làm s trỏ sang ký tự thứ 2, mất địa chỉ gốc. "
      + "Nếu dùng mảng char s[] thì s là địa chỉ hằng, không thể ++. Cần bỏ ++s hoặc dùng biến phụ.<br><br>"
      + "Chương trình sửa lại:<br><br>"
      + "<pre><code>int main(void) {\n"
      + "    char s[] = \"abcde\";\n"
      + "    int len = strlen(s);\n"
      + "    for (int i = 0; i &lt; len; i++)\n"
      + "        s[i] += 1;\n"
      + "    printf(\"'%s'\\n\", s);\n"
      + "    return 0;\n"
      + "}</code></pre>"
  },

  // ==================== ĐỀ SỐ 3 (Cuối kì 20201) ====================
  {
    id:512, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 1 (2.0 điểm)</strong><br><br>"
      + "(a) (0.5 điểm) Hãy cho biết sự khác nhau của hai cách khai báo giá trị: 'x' và \"x\". Hãy mô tả cách biểu diễn trong bộ nhớ của cả hai giá trị.<br><br>"
      + "(b) (1.5 điểm) Cho đoạn chương trình sau đây, hãy tìm ra ít nhất hai lỗi sai trong chương trình và sửa lại chương trình cho đúng:<br><br>"
      + "<pre><code>int main(void) {\n    char *s = \"abcde\";\n    int len = strlen(s);\n    for (int i = 0; i <= len; i++)\n        s[i] += 1;\n    return printf(\"'%s' is %d characters long\\n\", ++s, strlen(s));\n}</code></pre>",
    answer:"<strong>(a) Sự khác nhau giữa 'x' và \"x\":</strong><br><br>"
      + "- 'x': ký tự đơn (character literal), kiểu char, kích thước 1 byte, lưu mã ASCII 0x78 trong bộ nhớ.<br>"
      + "- \"x\": chuỗi ký tự (string literal), kiểu const char[2], kích thước 2 byte, lưu 'x' (0x78) và '\\0' (0x00) ở ô nhớ liền kề.<br>"
      + "Trong bộ nhớ: 'x' chiếm 1 ô nhớ (ví dụ địa chỉ 0x1000 chứa 0x78). "
      + "\"x\" chiếm 2 ô nhớ liên tiếp (0x2000 chứa 0x78, 0x2001 chứa 0x00).<br><br>"
      + "<strong>(b) Các lỗi trong chương trình:</strong><br><br>"
      + "<strong>Lỗi 1 - Ghi vào string literal (undefined behavior):</strong><br>"
      + "Con trỏ <code>char *s = \"abcde\";</code> trỏ đến hằng chuỗi trong vùng nhớ read-only. "
      + "Thao tác <code>s[i] += 1</code> ghi đè vào vùng nhớ không được phép, gây lỗi run-time (segmentation fault) hoặc undefined behavior.<br>"
      + "Sửa: dùng mảng có thể thay đổi <code>char s[] = \"abcde\";</code>.<br><br>"
      + "<strong>Lỗi 2 - Off-by-one: i &lt;= len (tràn bộ nhớ):</strong><br>"
      + "strlen(\"abcde\") = 5. Vòng lặp chạy i = 0..5 (6 lần). i = 5 truy cập s[5] là ký tự null '\\0', "
      + "ghi đè lên nó làm mất dấu kết thúc chuỗi, gây lỗi khi in hoặc xử lý chuỗi sau đó.<br>"
      + "Sửa: đổi thành <code>i &lt; len</code>.<br><br>"
      + "<strong>Lỗi 3 - ++s thay đổi địa chỉ gốc:</strong><br>"
      + "Nếu dùng mảng (char s[]), ++s là lỗi compile vì s là hằng địa chỉ. "
      + "Nếu giữ char* s, ++s làm s trỏ đến phần tử thứ 2, mất địa chỉ gốc, gây memory leak và in sai.<br>"
      + "Sửa: bỏ ++s, in trực tiếp s.<br><br>"
      + "Code hoàn chỉnh sau khi sửa:<br><br>"
      + "<pre><code>int main(void) {\n"
      + "    char s[] = \"abcde\";\n"
      + "    int len = strlen(s);\n"
      + "    for (int i = 0; i &lt; len; i++)\n"
      + "        s[i] += 1;\n"
      + "    printf(\"'%s'\\n\", s);\n"
      + "    return 0;\n"
      + "}</code></pre>"
  },
  {
    id:513, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 2 (2.0 điểm)</strong><br><br>"
      + "Một sinh viên xây dựng chức năng sắp xếp theo thứ tự kiểu Việt Nam (theo tên rồi mới đến họ và tên lót) từ "
      + "một danh sách họ và tên sinh viên của lớp như sau:<br><br>"
      + "<pre><code>// #include ...\nint i, j, n = 0;\nchar ds[500][30], tg[30];\nvoid bosung(); void sapxep(); void inds();\n\nint main() {\n    // hàm main\n}\n\nint NamePos(char *ht)\n{\n    i = strlen(ht) - 1;\n    while (ht[i] == ' ' && i > -1) i--;\n    while (ht[i] != ' ' && i > -1) i--;\n    return i + 1;\n}\n\nvoid sapxep() {\n    int i, j, k;\n    for (i = 0; i < n - 1; i++) {\n        k = i;\n        for (j = i + 1; j < n; j++)\n            if (strcmp(ds[k] + NamePos(ds[k]),\n                       ds[j] + NamePos(ds[j])) > 0) k = j;\n            else if (strcmp(ds[k] + NamePos(ds[k]),\n                            ds[j] + NamePos(ds[j])) == 0)\n                if (strcmp(ds[k], ds[j]) > 0) k = j;\n        if (k != i) {\n            strcpy(tg, ds[i]);\n            strcpy(ds[i], ds[k]);\n            strcpy(ds[k], tg);\n        }\n    }\n    printf(\"\\n Danh sach da duoc sap xep !!!\");\n    getch();\n}</code></pre><br>"
      + "Các hàm khác trong chương trình đều chuẩn nhưng khi in thì kết quả không được như ý, danh sách chỗ thì "
      + "sắp xếp được, chỗ thì không. Hãy tìm ra lỗi trong chương trình và chỉ ra lỗi là loại gì (compiler, runtime).",
    answer:"<strong>Phân tích lỗi:</strong><br><br>"
      + "Trong phiên bản này, hàm sapxep đã khai báo biến cục bộ <code>int i, j, k;</code> ở đầu hàm. "
      + "Tuy nhiên, biến i, j vẫn còn được khai báo là biến toàn cục ở đầu chương trình: <code>int i, j, n = 0;</code>. "
      + "Hàm NamePos không khai báo biến cục bộ nên nó sử dụng biến toàn cục i làm biến tạm để duyệt chuỗi. "
      + "Khi NamePos được gọi từ sapxep, nó thay đổi giá trị của biến toàn cục i (dù biến i cục bộ trong sapxep không bị ảnh hưởng, "
      + "nhưng biến i toàn cục bị thay đổi, ảnh hưởng đến các hàm khác có thể dùng nó).<br><br>"
      + "Tuy nhiên, vì sapxep dùng i cục bộ và NamePos dùng i toàn cục, nên lỗi này không trực tiếp ảnh hưởng đến sapxep trong phiên bản này. "
      + "Vấn đề thực sự có thể nằm ở chỗ: các hàm <code>bosung()</code> và <code>inds()</code> (không được hiển thị) "
      + "có thể cũng sử dụng các biến toàn cục i, j và gây xung đột với NamePos.<br><br>"
      + "<strong>Lỗi chính - Biến toàn cục không được khởi tạo/quản lý đúng cách (runtime logic error):</strong><br>"
      + "Biến n là biến toàn cục, dùng để đếm số phần tử. Nếu bosung() và các hàm khác không cập nhật n đúng cách, "
      + "hoặc nếu n không được khởi tạo, vòng lặp for trong sapxep sẽ chạy sai. "
      + "Đây là lỗi runtime (logic error) - chương trình vẫn biên dịch được nhưng chạy sai.<br><br>"
      + "Đề xuất sửa: khai báo biến cục bộ trong tất cả các hàm, loại bỏ biến toàn cục không cần thiết, "
      + "và truyền tham số rõ ràng giữa các hàm:<br><br>"
      + "<pre><code>int NamePos(char *ht)\n"
      + "{\n"
      + "    int pos = strlen(ht) - 1;\n"
      + "    while (pos &gt;= 0 &amp;&amp; ht[pos] == ' ') pos--;\n"
      + "    while (pos &gt;= 0 &amp;&amp; ht[pos] != ' ') pos--;\n"
      + "    return pos + 1;\n"
      + "}\n"
      + "\n"
      + "void sapxep(char ds[][30], int n) {\n"
      + "    int i, j, k;\n"
      + "    char tg[30];\n"
      + "    for (i = 0; i &lt; n - 1; i++) {\n"
      + "        k = i;\n"
      + "        for (j = i + 1; j &lt; n; j++) {\n"
      + "            int cmp = strcmp(ds[k] + NamePos(ds[k]),\n"
      + "                             ds[j] + NamePos(ds[j]));\n"
      + "            if (cmp &gt; 0) k = j;\n"
      + "            else if (cmp == 0 &amp;&amp; strcmp(ds[k], ds[j]) &gt; 0) k = j;\n"
      + "        }\n"
      + "        if (k != i) {\n"
      + "            strcpy(tg, ds[i]);\n"
      + "            strcpy(ds[i], ds[k]);\n"
      + "            strcpy(ds[k], tg);\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:514, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 3 (1.0 điểm)</strong><br><br>"
      + "Tinh chỉnh để nâng cao hiệu năng của chương trình sau:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n{\n    int i = 0, found = 0;\n    while ((!found) && (i < n)) {\n        float x = log(b) / log(2);\n        if (a[i] == x) found = 1;\n        else i++;\n    }\n    if (found) do_something;\n}</code></pre>",
    answer:"Các tinh chỉnh để nâng cao hiệu năng:<br><br>"
      + "1. <strong>Loop-invariant code motion:</strong> Tính <code>log(b)/log(2)</code> một lần trước vòng lặp, "
      + "vì giá trị không đổi trong suốt quá trình tìm kiếm.<br>"
      + "2. <strong>Thay while bằng for:</strong> Vòng lặp for rõ ràng hơn về mặt ngữ nghĩa, giúp compiler tối ưu tốt hơn.<br>"
      + "3. <strong>Dùng break thay biến found:</strong> Bỏ biến cờ found, dùng break để thoát ngay khi tìm thấy. "
      + "Giảm số lần kiểm tra điều kiện mỗi vòng lặp.<br>"
      + "4. <strong>So sánh số thực với epsilon:</strong> Dùng <code>fabs(a[i] - x) &lt; 1e-6</code> thay vì == "
      + "để tránh sai số do biểu diễn số thực dấu phẩy động (floating-point precision).<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n"
      + "{\n"
      + "    float x = log(b) / log(2);\n"
      + "    for (int i = 0; i &lt; n; i++) {\n"
      + "        if (fabs(a[i] - x) &lt; 1e-6) {\n"
      + "            do_something;\n"
      + "            break;\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },
  {
    id:515, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 4 (2.0 điểm)</strong><br><br>"
      + "Khi định nghĩa phép toán cộng ma trận (sử dụng operator overloading) cho cấu trúc Matrix được định nghĩa như sau:<br><br>"
      + "<pre><code>typedef struct {\n    int row, col;\n    float ** Data;\n} Matrix;</code></pre><br>"
      + "Một sinh viên nhận thấy, nếu thực hiện biểu thức C = A + B một vài lần thì kết quả OK, nhưng nếu biểu thức "
      + "đó nằm trong 1 vòng lặp lớn (hàng ngàn lần) thì kết quả không còn đúng, thậm chí khi tăng số lần lặp, "
      + "chương trình còn bị lỗi run-time, mặc dù các hàm cấp phát bộ nhớ, định nghĩa toán tử cộng ma trận SV đã "
      + "làm rất chuẩn. Em hãy cho biết tại sao (0.5đ) và đưa ra giải pháp (1.5đ).<br><br>"
      + "<pre><code>Matrix operator+(Matrix a, Matrix b) {\n    Matrix temp;\n    temp.row = a.row;\n    temp.col = a.col;\n    allocMatrix(temp);\n    /* Phần cộng ma trận ... */\n    return temp;\n}</code></pre>",
    answer:"<strong>Tại sao (0.5đ):</strong><br><br>"
      + "Hàm operator+ nhận tham số là Matrix a, Matrix b (truyền bằng trị - pass by value) và trả về Matrix (return by value). "
      + "Khi truyền bằng trị, trình biên dịch tạo bản sao (shallow copy) của các đối tượng Matrix. "
      + "Matrix chứa con trỏ float** Data, và shallow copy chỉ sao chép địa chỉ con trỏ, không cấp phát vùng nhớ mới. "
      + "Kết quả là có nhiều đối tượng cùng trỏ đến một vùng dữ liệu. "
      + "Khi một đối tượng bị hủy (kết thúc phạm vi), vùng nhớ được giải phóng, "
      + "các đối tượng khác trở thành dangling pointer. "
      + "Trong vòng lặp lớn (hàng nghìn lần), việc cấp phát và giải phóng liên tục dẫn đến "
      + "double free, memory corruption, và lỗi run-time.<br><br>"
      + "<strong>Giải pháp (1.5đ):</strong><br><br>"
      + "<strong>Cách 1 - Truyền tham chiếu hằng và dùng output parameter:</strong> "
      + "Tránh hoàn toàn việc sao chép không cần thiết.<br><br>"
      + "<pre><code>void addMatrix(const Matrix&amp; a, const Matrix&amp; b, Matrix&amp; c) {\n"
      + "    c.row = a.row; c.col = a.col;\n"
      + "    allocMatrix(c);\n"
      + "    for (int i = 0; i &lt; c.row; i++)\n"
      + "        for (int j = 0; j &lt; c.col; j++)\n"
      + "            c.Data[i][j] = a.Data[i][j] + b.Data[i][j];\n"
      + "}</code></pre><br>"
      + "<strong>Cách 2 - Định nghĩa copy constructor, destructor và assignment operator (C++, Rule of Three):</strong> "
      + "Đảm bảo deep copy khi sao chép.<br><br>"
      + "<pre><code>struct Matrix {\n"
      + "    int row, col;\n"
      + "    float** Data;\n"
      + "    Matrix() : row(0), col(0), Data(NULL) {}\n"
      + "    Matrix(const Matrix&amp; m) : row(m.row), col(m.col) {\n"
      + "        allocMatrix(*this);\n"
      + "        for (int i = 0; i &lt; row; i++)\n"
      + "            for (int j = 0; j &lt; col; j++)\n"
      + "                Data[i][j] = m.Data[i][j];\n"
      + "    }\n"
      + "    ~Matrix() { freeMatrix(*this); }\n"
      + "    Matrix&amp; operator=(const Matrix&amp; m) {\n"
      + "        if (this != &amp;m) {\n"
      + "            freeMatrix(*this);\n"
      + "            row = m.row; col = m.col;\n"
      + "            allocMatrix(*this);\n"
      + "            for (int i = 0; i &lt; row; i++)\n"
      + "                for (int j = 0; j &lt; col; j++)\n"
      + "                    Data[i][j] = m.Data[i][j];\n"
      + "        }\n"
      + "        return *this;\n"
      + "    }\n"
      + "};\n"
      + "\n"
      + "Matrix operator+(const Matrix&amp; a, const Matrix&amp; b) {\n"
      + "    Matrix temp;\n"
      + "    temp.row = a.row; temp.col = a.col;\n"
      + "    allocMatrix(temp);\n"
      + "    for (int i = 0; i &lt; temp.row; i++)\n"
      + "        for (int j = 0; j &lt; temp.col; j++)\n"
      + "            temp.Data[i][j] = a.Data[i][j] + b.Data[i][j];\n"
      + "    return temp;\n"
      + "}</code></pre>"
  },
  {
    id:516, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 5 (1.0 điểm)</strong><br><br>"
      + "Cho cấu trúc danh sách liên kết như sau:<br><br>"
      + "<pre><code>struct Node {\n    int data;\n    Node *next;\n};</code></pre><br>"
      + "Hãy viết hàm đảo ngược danh sách:<br>"
      + "<pre><code>Node* reverse(Node* head) { ... }</code></pre><br>"
      + "a) Sử dụng đệ quy (0.5 điểm)<br>"
      + "b) Không sử dụng đệ quy (0.5 điểm)",
    answer:"<strong>a) Giải pháp đệ quy (0.5đ):</strong><br><br>"
      + "Ý tưởng: Đảo ngược phần còn lại của danh sách (head-&gt;next), "
      + "sau đó cho head-&gt;next-&gt;next trỏ về head, "
      + "và head-&gt;next = NULL (head trở thành nút cuối).<br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    if (head == NULL || head-&gt;next == NULL)\n"
      + "        return head;\n"
      + "    Node* newHead = reverse(head-&gt;next);\n"
      + "    head-&gt;next-&gt;next = head;\n"
      + "    head-&gt;next = NULL;\n"
      + "    return newHead;\n"
      + "}</code></pre><br>"
      + "<strong>b) Giải pháp không đệ quy (0.5đ) - dùng 3 con trỏ:</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    Node *prev = NULL, *curr = head;\n"
      + "    while (curr != NULL) {\n"
      + "        Node* next = curr-&gt;next;\n"
      + "        curr-&gt;next = prev;\n"
      + "        prev = curr;\n"
      + "        curr = next;\n"
      + "    }\n"
      + "    return prev;\n"
      + "}</code></pre>"
  },
  {
    id:517, label:"Cuối kì 20201 - Đề 3",
    text:"<strong>Đề 3 - Câu 6 (2.0 điểm)</strong><br><br>"
      + "Theo bạn, kỹ thuật Template function có thể kết hợp vào đa năng hóa toán tử (operator overloading) được không? "
      + "Nếu được thì có lợi ích gì? Hãy minh họa bằng 1 ví dụ cụ thể liên quan đến đa năng hóa toán tử cho số phức.<br><br>"
      + "<pre><code>struct Complex {\n    int real, img;\n};</code></pre>",
    answer:"Có, kỹ thuật Template function có thể kết hợp với đa năng hóa toán tử (operator overloading). "
      + "Lợi ích: cho phép viết các toán tử tổng quát trên nhiều kiểu dữ liệu khác nhau (int, float, double, ...) "
      + "mà không phải viết nhiều phiên bản giống nhau, tiết kiệm code, dễ bảo trì và mở rộng.<br><br>"
      + "Với struct Complex đã cho, ta có thể chuyển thành template để hỗ trợ nhiều kiểu số:<br><br>"
      + "<pre><code>template &lt;typename T&gt;\n"
      + "struct Complex {\n"
      + "    T real, img;\n"
      + "    Complex(T r = 0, T i = 0) : real(r), img(i) {}\n"
      + "};\n"
      + "\n"
      + "// Đa năng hóa toán tử + (cộng)\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator+(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real + b.real, a.img + b.img);\n"
      + "}\n"
      + "\n"
      + "// Đa năng hóa toán tử - (trừ)\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator-(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real - b.real, a.img - b.img);\n"
      + "}\n"
      + "\n"
      + "// Sử dụng với int:\n"
      + "Complex&lt;int&gt; c1(1, 2), c2(3, 4);\n"
      + "Complex&lt;int&gt; c3 = c1 + c2;  // (4, 6)\n"
      + "Complex&lt;int&gt; c4 = c1 - c2;  // (-2, -2)\n"
      + "\n"
      + "// Sử dụng với double:\n"
      + "Complex&lt;double&gt; d1(1.5, 2.5), d2(3.5, 4.5);\n"
      + "Complex&lt;double&gt; d3 = d1 + d2;  // (5.0, 7.0)\n"
      + "Complex&lt;double&gt; d4 = d1 - d2;  // (-2.0, -2.0)</code></pre>"
  },
  {
    id:518, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 1 (2.0 điểm)</strong><br><br>"
      + "Theo bạn, kỹ thuật Template function có thể kết hợp vào đa năng hóa toán tử (operator overloading) được không? "
      + "Nếu được thì có lợi ích gì? Hãy minh họa bằng 1 ví dụ cụ thể liên quan đến đa năng hóa toán tử cho số phức.<br><br>"
      + "<pre><code>struct Complex {\n    int real, img;\n};</code></pre>",
    answer:"Có, kỹ thuật Template function hoàn toàn có thể kết hợp với đa năng hóa toán tử (operator overloading). "
      + "Lợi ích chính: tạo ra các toán tử tổng quát (generic) hoạt động trên nhiều kiểu dữ liệu khác nhau, "
      + "giúp tái sử dụng code, giảm trùng lặp và tăng khả năng bảo trì.<br><br>"
      + "Với struct Complex đã cho, ta chuyển thành template để có thể dùng với cả int, float, double, ...<br><br>"
      + "<pre><code>template &lt;typename T&gt;\n"
      + "struct Complex {\n"
      + "    T real, img;\n"
      + "    Complex(T r = 0, T i = 0) : real(r), img(i) {}\n"
      + "};\n"
      + "\n"
      + "// Đa năng hóa toán tử * (nhân) cho số phức\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator*(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real * b.real - a.img * b.img,\n"
      + "                        a.real * b.img + a.img * b.real);\n"
      + "}\n"
      + "\n"
      + "// Đa năng hóa toán tử + (cộng)\n"
      + "template &lt;typename T&gt;\n"
      + "Complex&lt;T&gt; operator+(const Complex&lt;T&gt;&amp; a, const Complex&lt;T&gt;&amp; b) {\n"
      + "    return Complex&lt;T&gt;(a.real + b.real, a.img + b.img);\n"
      + "}\n"
      + "\n"
      + "// Sử dụng với int:\n"
      + "Complex&lt;int&gt; c1(1, 2), c2(3, 4);\n"
      + "Complex&lt;int&gt; c3 = c1 + c2;  // (4, 6)\n"
      + "Complex&lt;int&gt; c4 = c1 * c2;  // (-5, 10)\n"
      + "\n"
      + "// Sử dụng với double:\n"
      + "Complex&lt;double&gt; d1(1.5, 2.5), d2(0.5, 1.5);\n"
      + "Complex&lt;double&gt; d3 = d1 * d2;  // (1.5*0.5 - 2.5*1.5, 1.5*1.5 + 2.5*0.5)</code></pre>"
  },
  {
    id:519, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 2 (2.0 điểm)</strong><br><br>"
      + "(a) (1.0 điểm) Hãy cho biết sự khác nhau giữa con trỏ (pointer) trong C/C++ và tham chiếu (reference) trong C++ "
      + "(gợi ý: so sánh về các mặt: định nghĩa, khởi tạo (initialization), gán (assignment/re-assignment), "
      + "địa chỉ trong bộ nhớ (memory address), phép toán).<br><br>"
      + "(b) (1.0 điểm) Cho đoạn chương trình sau đây:<br><br>"
      + "<pre><code>void swap(int x, int y) {\n    int temp = x;\n    x = y;\n    y = temp;\n}\n\nint main(int argc, char** argv) {\n    int x = 0;\n    int y = 1;\n    swap(x, y);\n    assert(x == 1);\n    return 0;\n}</code></pre><br>"
      + "(i) Hãy cho biết vai trò của câu lệnh assert và tại sao chương trình khi thực thi sẽ phát sinh failure với câu lệnh assert. (0.5 điểm)<br>"
      + "(ii) Hãy sửa lại chương trình trên theo hai cách: dùng C và dùng C++. (0.5 điểm)",
    answer:"<strong>(a) So sánh con trỏ (pointer) và tham chiếu (reference):</strong><br><br>"
      + "<strong>Định nghĩa:</strong> Con trỏ là biến lưu địa chỉ của biến khác (kiểu T*). "
      + "Tham chiếu là bí danh (alias) của một biến khác (kiểu T&amp;).<br>"
      + "<strong>Khởi tạo:</strong> Con trỏ có thể khai báo không khởi tạo (hoặc NULL/nullptr). "
      + "Tham chiếu phải được khởi tạo ngay khi khai báo và không thể tham chiếu đến null.<br>"
      + "<strong>Gán (re-assignment):</strong> Con trỏ có thể thay đổi để trỏ đến đối tượng khác. "
      + "Tham chiếu không thể thay đổi đối tượng tham chiếu sau khi khởi tạo (luôn gắn với cùng một đối tượng).<br>"
      + "<strong>Địa chỉ bộ nhớ:</strong> Bản thân con trỏ có địa chỉ riêng (chiếm 4 hoặc 8 byte tùy kiến trúc). "
      + "Tham chiếu không có địa chỉ riêng, nó chỉ là tên khác của biến gốc.<br>"
      + "<strong>Phép toán:</strong> Con trỏ hỗ trợ số học: ++, --, +, - (di chuyển trong mảng). "
      + "Tham chiếu không hỗ trợ số học con trỏ.<br>"
      + "<strong>Truy xuất giá trị:</strong> Dùng * để dereference con trỏ. "
      + "Tham chiếu được dùng trực tiếp như biến thường.<br>"
      + "<strong>NULL:</strong> Con trỏ có thể là NULL (hoặc nullptr trong C++11). "
      + "Tham chiếu luôn tham chiếu đến đối tượng hợp lệ.<br><br>"
      + "<strong>(b-i) Vai trò của assert và nguyên nhân failure:</strong><br><br>"
      + "assert(x == 1) là macro kiểm tra điều kiện x == 1 tại thời điểm chạy. "
      + "Nếu điều kiện sai, chương trình dừng và thông báo lỗi (assertion failed). "
      + "Hàm swap(int x, int y) nhận tham số theo kiểu truyền bằng trị (pass by value), "
      + "nghĩa là x và y trong hàm swap là bản sao cục bộ của x và y trong main. "
      + "Việc hoán đổi chỉ ảnh hưởng đến bản sao, không ảnh hưởng đến biến gốc. "
      + "Sau khi gọi swap(x, y), x trong main vẫn là 0, nên assert(x == 1) thất bại.<br><br>"
      + "<strong>(b-ii) Sửa chương trình:</strong><br><br>"
      + "<strong>Cách dùng C - truyền con trỏ:</strong><br><br>"
      + "<pre><code>void swap(int *x, int *y) {\n"
      + "    int temp = *x;\n"
      + "    *x = *y;\n"
      + "    *y = temp;\n"
      + "}\n"
      + "\n"
      + "int main() {\n"
      + "    int x = 0, y = 1;\n"
      + "    swap(&amp;x, &amp;y);\n"
      + "    assert(x == 1);\n"
      + "    return 0;\n"
      + "}</code></pre><br>"
      + "<strong>Cách dùng C++ - truyền tham chiếu:</strong><br><br>"
      + "<pre><code>void swap(int&amp; x, int&amp; y) {\n"
      + "    int temp = x;\n"
      + "    x = y;\n"
      + "    y = temp;\n"
      + "}\n"
      + "\n"
      + "int main() {\n"
      + "    int x = 0, y = 1;\n"
      + "    swap(x, y);\n"
      + "    assert(x == 1);\n"
      + "    return 0;\n"
      + "}</code></pre>"
  },
  {
    id:520, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 3 (1.0 điểm)</strong><br><br>"
      + "a) Hãy sửa lại đoạn chương trình sau đây cho đúng kết hợp tinh chỉnh code:<br><br>"
      + "<pre><code>typedef struct point { double x, y, z; } Point;\n\nint find_max_x_argument(int n, Point *elems) {\n    double max = 0;\n    int max_index = 0;\n    for (int i = 0; i < n; i++)\n        if (max < elems[i].x) {\n            max_index = i;\n            max = elems[i].x;\n        }\n    return max_index;\n}</code></pre><br>"
      + "b) Có một mảng các phần tử là các số nguyên biết rằng các phần tử trong mảng sẽ rơi vào một trong bốn trường hợp dưới đây:<br>"
      + "i) Các phần tử trong mảng sắp xếp tăng dần<br>"
      + "ii) Các phần tử trong mảng sắp xếp giảm dần<br>"
      + "iii) Các phần tử trong mảng tăng dần ở phần đầu và giảm dần ở phần cuối<br>"
      + "iv) Các phần tử trong mảng giảm dần ở phần đầu và tăng dần ở phần cuối<br><br>"
      + "Đưa ra một phương án tối ưu nhất để tìm kiếm phần tử lớn nhất trong dãy (1.0 điểm)",
    answer:"<strong>a) Sửa lỗi và tinh chỉnh find_max_x_argument:</strong><br><br>"
      + "Lỗi: Biến max được khởi tạo bằng 0. Nếu tất cả giá trị x trong mảng đều âm (ví dụ: -5, -3, -1), "
      + "thì max = 0 luôn lớn hơn tất cả các x, vòng lặp không cập nhật max_index, "
      + "kết quả trả về 0 (chỉ số đầu tiên) dù phần tử có x lớn nhất lại là -1 ở vị trí khác, dẫn đến sai.<br><br>"
      + "Cách sửa: Khởi tạo max bằng giá trị x của phần tử đầu tiên (elems[0].x). "
      + "Nếu n &lt;= 0, trả về -1 để báo lỗi (hoặc xử lý tùy yêu cầu).<br><br>"
      + "<pre><code>int find_max_x_argument(int n, Point *elems) {\n"
      + "    if (n &lt;= 0) return -1;\n"
      + "    double max = elems[0].x;\n"
      + "    int max_index = 0;\n"
      + "    for (int i = 1; i &lt; n; i++) {\n"
      + "        if (elems[i].x &gt; max) {\n"
      + "            max = elems[i].x;\n"
      + "            max_index = i;\n"
      + "        }\n"
      + "    }\n"
      + "    return max_index;\n"
      + "}</code></pre><br>"
      + "<strong>b) Tìm phần tử lớn nhất trong mảng đặc biệt - O(log n):</strong><br><br>"
      + "Đây là bài toán tìm peak (đỉnh) trên mảng có thể ở một trong bốn dạng: "
      + "tăng dần, giảm dần, tăng rồi giảm (mountain), giảm rồi tăng (valley). "
      + "Với tất cả các trường hợp, ta có thể dùng biến thể của tìm kiếm nhị phân (binary search) "
      + "với độ phức tạp O(log n).<br><br>"
      + "Ý tưởng: So sánh a[mid] với a[mid+1]:<br>"
      + "- Nếu a[mid] &lt; a[mid+1]: đang ở nhánh tăng, maximum nằm bên phải (lo = mid + 1)<br>"
      + "- Nếu a[mid] &gt; a[mid+1]: đang ở nhánh giảm, maximum là mid hoặc bên trái (hi = mid)<br><br>"
      + "Phương pháp này hoạt động cho mảng tăng (kết quả ở cuối), "
      + "giảm (kết quả ở đầu), và hình chuông (mountain). "
      + "Riêng trường hợp valley (giảm rồi tăng), giá trị lớn nhất là một trong hai đầu mút, "
      + "có thể kiểm tra riêng.<br><br>"
      + "<pre><code>int findMax(int a[], int n) {\n"
      + "    if (n &lt;= 0) return -1;\n"
      + "    if (n == 1) return a[0];\n"
      + "    // Kiểm tra biên cho trường hợp giảm dần hoặc valley\n"
      + "    if (a[0] &gt;= a[1]) return a[0];\n"
      + "    if (a[n-1] &gt;= a[n-2]) return a[n-1];\n"
      + "    // Modified binary search tìm peak\n"
      + "    int lo = 0, hi = n - 1;\n"
      + "    while (lo &lt; hi) {\n"
      + "        int mid = lo + (hi - lo) / 2;\n"
      + "        if (a[mid] &lt; a[mid + 1])\n"
      + "            lo = mid + 1;\n"
      + "        else\n"
      + "            hi = mid;\n"
      + "    }\n"
      + "    return a[lo];\n"
      + "}</code></pre>"
  },
  {
    id:521, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 4 (2.0 điểm)</strong><br><br>"
      + "a) Vì sao trong ngôn ngữ lập trình C, không cho phép gán hai mảng nhưng lại có thể gán 2 biến kiểu "
      + "struct có phần tử là các mảng? (0.5đ)<br><br>"
      + "b) Một sinh viên cài đặt phép * cho hai mảng như sau:<br><br>"
      + "<pre><code>typedef struct array {\n    int n;\n    float* data;\n} Array;\n\nvoid newArray(Array &a) {\n    a.data = new float[n];\n}\n\nArray operator*(Array a, Array b) {\n    Array temp;\n    temp.n = a.n;\n    newArray(temp);\n    for (int i = 0; i < n; i++)\n        temp.data[i] = a.data[i] * b.data[i];\n    return temp;\n}\n\nvoid main() {\n    Array a, b, c;\n    // Giả sử đã có khởi tạo và nhập dữ liệu cho hai mảng a, b\n    for (int i = 0; i < 10000; i++)\n        c = a * b;\n}</code></pre><br>"
      + "Hãy dự đoán vấn đề gì có thể xảy ra với đoạn chương trình này? (0.5 điểm)<br>"
      + "Cài đặt giải pháp khắc phục vấn đề trên (1.0 điểm)",
    answer:"<strong>a) Vì sao C không cho gán mảng nhưng gán được struct chứa mảng?</strong><br><br>"
      + "Trong C, tên mảng là địa chỉ hằng (constant pointer), không thể gán vì không phải l-value. "
      + "Tuy nhiên, struct là kiểu dữ liệu do người dùng định nghĩa, và C hỗ trợ gán struct bằng cách "
      + "sao chép toàn bộ bộ nhớ (bitwise copy) giữa hai biến struct, kể cả các mảng bên trong. "
      + "Trình biên dịch tự động tạo code sao chép nội dung mảng khi gán struct (tương tự memcpy). "
      + "Do đó, gán struct chứa mảng là hợp lệ.<br><br>"
      + "<strong>b) Dự đoán vấn đề (0.5đ):</strong><br><br>"
      + "Tương tự bài toán ma trận: Cấu trúc Array chứa con trỏ float* data. "
      + "Hàm operator* nhận tham số là Array a, Array b (truyền bằng trị, shallow copy). "
      + "Khi trả về Array temp (return by value), trình biên dịch tạo bản sao shallow của temp. "
      + "Cả temp và bản sao cùng trỏ đến vùng nhớ data. "
      + "Khi temp bị hủy (kết thúc hàm), vùng nhớ data bị giải phóng, "
      + "bản sao tạm thời có con trỏ treo (dangling pointer). "
      + "Trong vòng lặp 10000 lần, cấp phát và giải phóng liên tục gây rò rỉ bộ nhớ (memory leak) "
      + "và lỗi run-time (double free, memory corruption).<br>"
      + "Ngoài ra, vòng lặp <code>for (int i = 0; i &lt; n; i++)</code> dùng biến n không rõ nguồn gốc "
      + "(thiếu tham chiếu đến a.n), gây lỗi compile.<br><br>"
      + "<strong>Giải pháp (1.0đ):</strong> Định nghĩa copy constructor, destructor, operator= (Rule of Three) "
      + "để đảm bảo deep copy, hoặc dùng pass-by-reference với output parameter.<br><br>"
      + "<pre><code>struct Array {\n"
      + "    int n;\n"
      + "    float* data;\n"
      + "    Array() : n(0), data(NULL) {}\n"
      + "    Array(const Array&amp; a) : n(a.n) {\n"
      + "        data = new float[n];\n"
      + "        for (int i = 0; i &lt; n; i++)\n"
      + "            data[i] = a.data[i];\n"
      + "    }\n"
      + "    ~Array() { delete[] data; }\n"
      + "    Array&amp; operator=(const Array&amp; a) {\n"
      + "        if (this != &amp;a) {\n"
      + "            delete[] data;\n"
      + "            n = a.n;\n"
      + "            data = new float[n];\n"
      + "            for (int i = 0; i &lt; n; i++)\n"
      + "                data[i] = a.data[i];\n"
      + "        }\n"
      + "        return *this;\n"
      + "    }\n"
      + "};\n"
      + "\n"
      + "Array operator*(const Array&amp; a, const Array&amp; b) {\n"
      + "    Array temp;\n"
      + "    temp.n = a.n;\n"
      + "    temp.data = new float[temp.n];\n"
      + "    for (int i = 0; i &lt; temp.n; i++)\n"
      + "        temp.data[i] = a.data[i] * b.data[i];\n"
      + "    return temp;\n"
      + "}</code></pre>"
  },
  {
    id:522, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 5 (1.0 điểm)</strong><br><br>"
      + "Cho cấu trúc danh sách liên kết như sau:<br><br>"
      + "<pre><code>struct Node {\n    int data;\n    Node *next;\n};</code></pre><br>"
      + "Hãy viết hàm đảo ngược danh sách:<br>"
      + "<pre><code>Node* reverse(Node* head) { ... }</code></pre><br>"
      + "a) Sử dụng đệ quy (0.5 điểm)<br>"
      + "b) Không sử dụng đệ quy (0.5 điểm)",
    answer:"<strong>a) Sử dụng đệ quy (0.5đ):</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    if (head == NULL || head-&gt;next == NULL)\n"
      + "        return head;\n"
      + "    Node* newHead = reverse(head-&gt;next);\n"
      + "    head-&gt;next-&gt;next = head;\n"
      + "    head-&gt;next = NULL;\n"
      + "    return newHead;\n"
      + "}</code></pre><br>"
      + "Giải thích: Base case là danh sách rỗng hoặc 1 nút. "
      + "Gọi đệ quy trên head-&gt;next để đảo ngược phần còn lại, thu được newHead là đầu mới. "
      + "Sau đó, nút cuối của phần đã đảo (head-&gt;next) trỏ ngược về head, "
      + "và head-&gt;next = NULL (head giờ là nút cuối).<br><br>"
      + "<strong>b) Không sử dụng đệ quy (0.5đ):</strong><br><br>"
      + "<pre><code>Node* reverse(Node* head) {\n"
      + "    Node *prev = NULL, *curr = head;\n"
      + "    while (curr != NULL) {\n"
      + "        Node* next = curr-&gt;next;\n"
      + "        curr-&gt;next = prev;\n"
      + "        prev = curr;\n"
      + "        curr = next;\n"
      + "    }\n"
      + "    return prev;\n"
      + "}</code></pre><br>"
      + "Giải thích: Dùng 3 con trỏ prev, curr, next duyệt danh sách một lần. "
      + "Với mỗi curr, đảo ngược liên kết curr-&gt;next = prev, "
      + "rồi dịch prev và curr sang phải. Kết thúc, prev là đầu danh sách mới."
  },
  {
    id:523, label:"Cuối kì 20201 - Đề 4",
    text:"<strong>Đề 4 - Câu 6 (1.0 điểm)</strong><br><br>"
      + "Tinh chỉnh để nâng cao hiệu năng của chương trình sau:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n{\n    int i = 0, found = 0;\n    while ((!found) && (i < n)) {\n        float x = log(b) / log(2);\n        if (a[i] == x) found = 1;\n        else i++;\n    }\n    if (found) do_something;\n}</code></pre>",
    answer:"Các kỹ thuật tinh chỉnh:<br><br>"
      + "1. <strong>Loop-invariant code motion:</strong> Biểu thức <code>log(b) / log(2)</code> "
      + "không phụ thuộc vào vòng lặp, nên tính một lần trước vòng lặp.<br>"
      + "2. <strong>Thay while bằng for:</strong> Vòng lặp for tập trung khởi tạo, điều kiện, bước nhảy, "
      + "giúp compiler tối ưu tốt hơn và code dễ đọc.<br>"
      + "3. <strong>Dùng break thay biến cờ found:</strong> Thoát ngay khi tìm thấy, "
      + "không cần biến phụ và điều kiện phức tạp.<br>"
      + "4. <strong>So sánh số thực với epsilon:</strong> Dùng <code>fabs(a[i] - target) &lt; 1e-6</code> "
      + "thay vì == để tránh sai số floating-point.<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n"
      + "{\n"
      + "    float target = log(b) / log(2);\n"
      + "    for (int i = 0; i &lt; n; i++) {\n"
      + "        if (fabs(a[i] - target) &lt; 1e-6) {\n"
      + "            do_something;\n"
      + "            break;\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre>"
  },

  // ==================== ÔN TẬP ====================
  {
    id:524, label:"Ôn tập KTLT",
    text:"<strong>Câu 1. Tinh chỉnh switch-case xếp loại học sinh</strong><br><br>"
      + "Theo thống kê, kết quả xếp loại học sinh của 1 trường PTTH hàng năm có 60% HS đạt điểm trung bình (C), "
      + "20% đạt điểm khá (B), 8% xếp loại giỏi (A) và 12% xếp loại kém (D). "
      + "Đoạn code để đếm số HS mỗi loại. Hãy tinh chỉnh và giải thích lý do:<br><br>"
      + "<pre><code>for (i = 0; i < sohs; i++) {\n    switch (HS[i].XL) {\n        case 'A': Gioi++; break;\n        case 'B': Kha++; break;\n        case 'C': TB++; break;\n        default: Kem++;\n    }\n}</code></pre>",
    answer:"Vấn đề: Thứ tự các case trong switch không tối ưu cho branch prediction. "
      + "CPU hiện đại dự đoán nhánh dựa trên lịch sử. Nếu case đầu tiên (A - 8% - ít gặp nhất) được đặt đầu tiên, "
      + "CPU sẽ liên tục dự đoán sai (misprediction), gây giảm hiệu năng đáng kể trong vòng lặp lớn.<br><br>"
      + "Các tinh chỉnh:<br><br>"
      + "1. <strong>Sắp xếp các case theo tần suất giảm dần:</strong> "
      + "Đặt case có xác suất cao nhất lên đầu để CPU dự đoán đúng nhiều hơn. "
      + "Thứ tự tối ưu: C (60%) → B (20%) → D (12%) → A (8%).<br>"
      + "2. <strong>Giảm thiểu branch misprediction:</strong> Nếu có thể, dùng if-else thay cho switch "
      + "khi số trường hợp ít và tần suất chênh lệch lớn, vì if-else cho phép compiler tối ưu tốt hơn.<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>for (i = 0; i &lt; sohs; i++) {\n"
      + "    switch (HS[i].XL) {\n"
      + "        case 'C': TB++; break;    // 60% - đặt đầu\n"
      + "        case 'B': Kha++; break;   // 20%\n"
      + "        case 'D': Kem++; break;   // 12%\n"
      + "        case 'A': Gioi++; break;  // 8% - đặt cuối\n"
      + "    }\n"
      + "}</code></pre><br>"
      + "Hoặc dùng if-else:<br><br>"
      + "<pre><code>for (i = 0; i &lt; sohs; i++) {\n"
      + "    char xl = HS[i].XL;\n"
      + "    if (xl == 'C') TB++;\n"
      + "    else if (xl == 'B') Kha++;\n"
      + "    else if (xl == 'D') Kem++;\n"
      + "    else if (xl == 'A') Gioi++;\n"
      + "}</code></pre>"
  },
  {
    id:525, label:"Ôn tập KTLT",
    text:"<strong>Câu 2. Tối ưu vòng lặp lồng</strong><br><br>"
      + "Yêu cầu viết lại đoạn chương trình dưới đây sau khi thực hiện các tối ưu và tinh chỉnh cần thiết để tăng hiệu năng chương trình:<br><br>"
      + "<pre><code>for (int i = 0; i < 20000; i++)\n    for (int j = 0; j < 5; j++)\n        sum += sin(i / 16 + 2 * j);</code></pre>",
    answer:"Các tối ưu hóa:<br><br>"
      + "1. <strong>Loop-invariant code motion:</strong> "
      + "Với mỗi i, biểu thức <code>i / 16</code> được tính 5 lần (mỗi lần lặp j). "
      + "Nên tính một lần ở vòng ngoài.<br>"
      + "2. <strong>Strength reduction:</strong> Biến đổi <code>2 * j</code> thành phép cộng dồn.<br>"
      + "3. <strong>Loop unrolling (tháo vòng lặp trong):</strong> "
      + "Vòng lặp trong chỉ có 5 lần lặp, có thể tháo hoàn toàn để giảm overhead.<br><br>"
      + "Code sau khi tối ưu:<br><br>"
      + "<pre><code>for (int i = 0; i &lt; 20000; i++) {\n"
      + "    double base = i / 16.0;\n"
      + "    sum += sin(base) + sin(base + 2.0) + sin(base + 4.0)\n"
      + "         + sin(base + 6.0) + sin(base + 8.0);\n"
      + "}</code></pre><br>"
      + "Giải thích: Các tối ưu này giúp tăng tốc độ bằng cách: "
      + "(1) giảm số lần tính toán i/16 từ 100.000 (20000*5) xuống 20.000, "
      + "(2) tháo bỏ vòng lặp trong giúp giảm overhead của việc kiểm tra điều kiện và tăng j, "
      + "(3) giúp compiler có thể áp dụng các tối ưu khác (SIMD, instruction-level parallelism)."
  },
  {
    id:526, label:"Ôn tập KTLT",
    text:"<strong>Câu 3. Tinh chỉnh findK</strong><br><br>"
      + "Tinh chỉnh để nâng cao hiệu năng của chương trình sau và giải thích lý do tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n{\n    int i = 0, found = 0;\n    while ((!found) && (i < n)) {\n        float x = log(b) / log(2);\n        if (fabs(a[i] - x) < 1e-9) found = 1;\n        else i++;\n    }\n    if (found) do_something;\n}</code></pre>",
    answer:"Các tinh chỉnh:<br><br>"
      + "1. <strong>Loop-invariant code motion:</strong> "
      + "Biểu thức <code>log(b) / log(2)</code> được tính lại mỗi lần lặp. "
      + "Vì b không thay đổi, giá trị này là hằng số trong suốt vòng lặp. "
      + "Đưa ra ngoài vòng lặp để tính một lần.<br>"
      + "2. <strong>Thay while bằng for:</strong> Cấu trúc for rõ ràng hơn. "
      + "Khởi tạo, điều kiện dừng, và bước nhảy được đặt ở một chỗ.<br>"
      + "3. <strong>Dùng break thay biến found:</strong> Thoát vòng lặp ngay khi tìm thấy. "
      + "Giảm một lần kiểm tra điều kiện mỗi vòng lặp.<br>"
      + "4. <strong>Đặt tên biến rõ ràng:</strong> Đổi x thành target để code dễ hiểu hơn.<br><br>"
      + "Code sau khi tinh chỉnh:<br><br>"
      + "<pre><code>void findK(float b, float *a, int n)\n"
      + "{\n"
      + "    float target = log(b) / log(2);\n"
      + "    for (int i = 0; i &lt; n; i++) {\n"
      + "        if (fabs(a[i] - target) &lt; 1e-9) {\n"
      + "            do_something;\n"
      + "            break;\n"
      + "        }\n"
      + "    }\n"
      + "}</code></pre><br>"
      + "Lý do tinh chỉnh: Các thay đổi giúp giảm số phép tính từ O(n) xuống O(1) cho biểu thức log, "
      + "cải thiện branch prediction, và làm code sáng sủa, dễ bảo trì hơn."
  },
  {
    id:527, label:"Ôn tập KTLT",
    text:"<strong>Câu 4. Dãy số phụ thuộc tương hỗ</strong><br><br>"
      + "Cho 2 dãy số phụ thuộc tương hỗ lẫn nhau:<br><br>"
      + "X = 1, 2, 3, 4, 16, 26, 58, 94, 218, 354, 809, 1314, ...<br>"
      + "Y = 2, 4, 6, 8, 14, 31, 50, 113, 184, 420, 682, 1560, ...<br><br>"
      + "Gợi ý:<br>"
      + "16 = 1 + 4 + 3 + 8, &nbsp; 26 = 2 + 6 + 4 + 14<br>"
      + "14 = 2 + 2 + 6 + 4, &nbsp; 31 = 4 + 3 + 8 + 16<br><br>"
      + "Hãy viết chương trình tính và in ra tổng n phần tử của dãy X và Y (n > 0).<br>"
      + "a. Dùng đệ quy tính giá trị phần tử thứ n của X và của Y rồi viết hàm tính tổng<br>"
      + "b. Không dùng đệ quy viết hàm tính tổng luôn",
    answer:"Phân tích công thức truy hồi từ gợi ý:<br><br>"
      + "X[1] = 1, X[2] = 2, X[3] = 3, X[4] = 4<br>"
      + "Y[1] = 2, Y[2] = 4, Y[3] = 6, Y[4] = 8<br><br>"
      + "Với n &gt; 4:<br>"
      + "X[n] = X[n-4] + X[n-1] + Y[n-3] + Y[n-2]<br>"
      + "Y[n] = Y[n-4] + Y[n-1] + X[n-3] + X[n-2]<br><br>"
      + "Hay viết gọn:<br>"
      + "X[n] = X[n-4] + X[n-1] + Y[n-3] + Y[n-2]<br>"
      + "Y[n] = Y[n-4] + Y[n-1] + X[n-3] + X[n-2]<br><br>"
      + "<strong>a) Giải pháp đệ quy:</strong><br><br>"
      + "<pre><code>#include &lt;stdio.h&gt;\n"
      + "\n"
      + "int X(int n) {\n"
      + "    if (n == 1) return 1;\n"
      + "    if (n == 2) return 2;\n"
      + "    if (n == 3) return 3;\n"
      + "    if (n == 4) return 4;\n"
      + "    return X(n-4) + X(n-1) + Y(n-3) + Y(n-2);\n"
      + "}\n"
      + "\n"
      + "int Y(int n) {\n"
      + "    if (n == 1) return 2;\n"
      + "    if (n == 2) return 4;\n"
      + "    if (n == 3) return 6;\n"
      + "    if (n == 4) return 8;\n"
      + "    return Y(n-4) + Y(n-1) + X(n-3) + X(n-2);\n"
      + "}\n"
      + "\n"
      + "int sumX(int n) {\n"
      + "    int s = 0;\n"
      + "    for (int i = 1; i &lt;= n; i++)\n"
      + "        s += X(i);\n"
      + "    return s;\n"
      + "}\n"
      + "\n"
      + "int sumY(int n) {\n"
      + "    int s = 0;\n"
      + "    for (int i = 1; i &lt;= n; i++)\n"
      + "        s += Y(i);\n"
      + "    return s;\n"
      + "}\n"
      + "\n"
      + "int main() {\n"
      + "    int n;\n"
      + "    printf(\"Nhap n: \");\n"
      + "    scanf(\"%d\", &amp;n);\n"
      + "    printf(\"Tong %d phan tu cua X: %d\\n\", n, sumX(n));\n"
      + "    printf(\"Tong %d phan tu cua Y: %d\\n\", n, sumY(n));\n"
      + "    return 0;\n"
      + "}</code></pre><br>"
      + "<strong>b) Giải pháp không đệ quy (dùng vòng lặp - quy hoạch động):</strong><br><br>"
      + "<pre><code>#include &lt;stdio.h&gt;\n"
      + "\n"
      + "void tinhTong(int n, int *sumX, int *sumY) {\n"
      + "    if (n &lt;= 0) { *sumX = 0; *sumY = 0; return; }\n"
      + "    \n"
      + "    int X[1000], Y[1000];\n"
      + "    // Khởi tạo 4 phần tử đầu\n"
      + "    int initX[] = {0, 1, 2, 3, 4};  // X[1..4]\n"
      + "    int initY[] = {0, 2, 4, 6, 8};  // Y[1..4]\n"
      + "    for (int i = 1; i &lt;= 4 &amp;&amp; i &lt;= n; i++) {\n"
      + "        X[i] = initX[i];\n"
      + "        Y[i] = initY[i];\n"
      + "    }\n"
      + "    \n"
      + "    // Tính các phần tử tiếp theo\n"
      + "    for (int i = 5; i &lt;= n; i++) {\n"
      + "        X[i] = X[i-4] + X[i-1] + Y[i-3] + Y[i-2];\n"
      + "        Y[i] = Y[i-4] + Y[i-1] + X[i-3] + X[i-2];\n"
      + "    }\n"
      + "    \n"
      + "    // Tính tổng\n"
      + "    *sumX = 0; *sumY = 0;\n"
      + "    for (int i = 1; i &lt;= n; i++) {\n"
      + "        *sumX += X[i];\n"
      + "        *sumY += Y[i];\n"
      + "    }\n"
      + "}\n"
      + "\n"
      + "int main() {\n"
      + "    int n, sumX, sumY;\n"
      + "    printf(\"Nhap n: \");\n"
      + "    scanf(\"%d\", &amp;n);\n"
      + "    tinhTong(n, &amp;sumX, &amp;sumY);\n"
      + "    printf(\"Tong %d phan tu cua X: %d\\n\", n, sumX);\n"
      + "    printf(\"Tong %d phan tu cua Y: %d\\n\", n, sumY);\n"
      + "    return 0;\n"
      + "}</code></pre><br>"
      + "Giải thích: Giải pháp không đệ quy (quy hoạch động) hiệu quả hơn vì tránh tính toán lại "
      + "các giá trị giống nhau nhiều lần. Đệ quy trần (naive recursion) có độ phức tạp O(2^n) "
      + "do tính lại X và Y cho cùng n nhiều lần, trong khi quy hoạch động chỉ mất O(n)."
  }
];

// =============================================
// Render function for essay questions
// =============================================
function renderEssay() {
  const container = document.getElementById('questions-container');
  let html = '<p style="text-align:center;color:#888;margin-bottom:16px;font-style:italic">📝 Đề tự luận — bấm "Xem đáp án" để xem gợi ý lời giải</p>';
  ktltEssay.forEach((item, idx) => {
    html += `<div class="question" style="position:relative">
      <h3 style="border-left-color:#ff9800">${item.text}</h3>
      <button class="show-answer-btn" onclick="toggleAnswer(${idx})">📖 Xem đáp án</button>
      <div class="essay-answer" id="essayAns${idx}">
        <div class="answer-content">${item.answer || 'Chưa có đáp án.'}</div>
      </div>
    </div>`;
  });
  container.innerHTML = html;
  document.getElementById('stats').textContent = ktltEssay.length + ' câu tự luận';
}

function toggleAnswer(idx) {
  const el = document.getElementById('essayAns' + idx);
  const btn = el.previousElementSibling;
  el.classList.toggle('show');
  btn.textContent = el.classList.contains('show') ? '🙈 Ẩn đáp án' : '📖 Xem đáp án';
}
